### PR TITLE
Better .travis build

### PR DESCRIPTION
**Pull request by dileping**
- Linux build + tests
- Automatic carthage binary release

To enable automatic release, just generate your own API key with `travis setup releases`. Here is a full [instruction from Carthage](https://github.com/Carthage/Carthage#use-travis-ci-to-upload-your-tagged-prebuild-frameworks)

### CODE REVIEW

**Comment by benloong** [comment]
Nice, but I don't know why `testParseNumber` failed. All test passed on my Ubuntu 14.04 machine. Is c function `strtod` parse double lead this?

**Comment by dileping** [comment]
Very strange. I tested it before sending the PR here: [https://travis-ci.org/crossroadlabs/TidyJSON/jobs/111675663](https://travis-ci.org/crossroadlabs/TidyJSON/jobs/111675663)

**Comment by benloong** [comment]
Yes, your test passed too.
in PR test 
`let json = try? JSON.parse("-120003e-1")
        XCTAssertEqual(json!.double!, -120003e-1)` 
 parse result is  `(-1.2000299999999999e-11)`

that's too weird. I can't figure it out.

**Comment by benloong** [comment]
I know how to fix this. 
http://en.cppreference.com/w/c/string/byte/strtof

> Function discards any whitespace characters (as determined by std::isspace()) until first non-whitespace character is found. Then it takes as many characters as possible to form a valid floating point representation and converts them to floating point value

**Comment by dileping** [comment]
Great! Let me know if you need any help.

**Comment by dileping** [comment]
You know, I think it works correctly. It's just incorrect to use XCTAssertEqual on float values

**Pull request merged**
